source 'https://rubygems.org'
ruby '2.0.0'
#ruby-gemset=taxi

gem 'rails', '4.0.4'
gem 'sprockets', '2.11.0'
gem 'bcrypt-ruby', '3.1.2'
gem 'faker', '1.1.2'
gem 'sqlite3', '1.3.8'

gem 'sass-rails', '4.0.1'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'delayed_job_active_record'

group :development, :test do
  gem 'rspec-rails', '2.13.1'
  gem 'factory_girl_rails', '4.2.0'
end

group :test do
  gem 'webmock'
end
